# Generated by Django 3.2.8 on 2021-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='letter',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
